@character chipher "Cipher"
@portrait chipher assets/cipher.png
@voice chipher assets/ciphersound.wav

@character evil "Evil Messed Up Cipher"
@portrait evil assets/evil.png
@voice evil assets/evilsound.wav


chipher: what a lovely day of hacking n stuffs
chipher: jumping around nodes, getting into places im not supposed to >:)
chipher: oooo thats a good one. im gonna get into it
chipher: this stuff is so easy its literally just pressing the directions n they let you in
[signal: Tut1End]
