@character chipher "Cipher"
@portrait chipher assets/cipher.png
@voice chipher assets/ciphersound.wav

@character evil "Evil Messed Up Cipher"
@portrait evil assets/evil.png
@voice evil assets/evilsound.wav


chipher: lmao nice
chipher: why did they have 11 terabytes of brussel sprout jpegs.
evil: it was ME
evil: brussel sprouts are WAY better than peaches
chipher: im sorry to tell you but that's objectively wrong
evil: im sending you to eeby deeby
[signal: Tut2End]
