@character chipher "Cipher"
@portrait chipher assets/cipher.png
@voice chipher assets/ciphersound.wav

@character evil "Evil Messed Up Cipher"
@portrait evil assets/evil.png
@voice evil assets/evilsound.wav


chipher: lmao nice
chipher: why did they have 11 terabytes of pear jpegs.
evil: it was ME
evil: pears are WAY better than peaches
chipher: yeah no, that wrong
evil: aight im getting ur ass
[signal: Tut2End]
