@character chipher "Cipher"
@portrait chipher assets/cipher.png
@voice chipher assets/ciphersound.wav

@character evil "Evil Messed Up Cipher"
@portrait evil assets/evil.png
@voice evil assets/evilsound.wav


chipher: what is this stuff
evil: it is my evil hacker juice of EVIL
chipher: im just gonna hop nodes outta here
evil: too bad that my EVIL hacker juice of EVIL can flood the system
chipher: what if i just. run faster
[signal: Tut3End]
